coverage:
  status:
    patch:
      default:
        target: auto
        threshold: 5%
        only_pulls: true
    project:
      default:
        target: auto
        threshold: 5%
        only_pulls: true
ignore:
  - "gen"
  - "test"
  - "sim"
  - "cmd"
  - "**/*_test.go"
  - "**/cbor_gen.go"
